### ISSUE TITLE
accessing speciment management should be done in retriever API file

### ISSUE THREAD

**Issue by anatolydryga** [esherm/geneTherapyPatientReportMaker#10]
# grab all possible GTSP samples, and pick the ones we care about for this report

GTSPDBconn = dbConnect(MySQL(), group="specimen_management")
sets = dbGetQuery(GTSPDBconn, "SELECT SpecimenAccNum, Trial, CellType, Patient,
                                      Timepoint, SamplePrepMethod, VCN
                               FROM gtsp;")
dbDisconnect(GTSPDBconn)
sets = merge(sets, sampleName_GTSP, by.x="SpecimenAccNum" , by.y="GTSP")

current; we just want simple call

get_speciment(GTSP)

**Comment by esherm** [comment]
Should go in its own project, rather than intSiteRetriever

**Comment by anatolydryga** [comment]
moved to function still pulls all data from DB

**Comment by anatolydryga** [comment]
should we get repeats or only process unique GTSP?

**Comment by esherm** [comment]
fully resolved with 874f73200e0001cf4750a5950b449f363dc417db
